### ISSUE TITLE
Milestone 2 Deliverables

### ISSUE THREAD

**Issue by jnederlo** [UBC-MDS/pypuck#11]
- [x] Player stats function + tests. #24 
- [x] Team stats function + tests. #32 
- [x] Draft function + tests. #33 
- [ ] Attendance function + tests. #34

**Comment by jnederlo** [comment]
Will need to use poetry to add additional function documentation to python's readthedocs.io. Follow the tutorial in the book "The Whole Game".
