### ISSUE TITLE
attendance function and its tests for milestone 2

### ISSUE THREAD

**Issue by chuusan** [UBC-MDS/pypuck#30]
Milestone 2 expected outcomes: competed `attendance` function and 2 unit tests covering at least 2 - 3 edge cases. The requirements are detailed as follows:

- [x] Iteratively code up the function.
- [x] 2 unit tests.
- [x] The unit test should cover at least 2 - 3 edge cases.
- [x] The test(s) should cover all branches of program flow (i.e. both sides of an if-statement).
- [x] Update the documentation in response to the coding and the tests for any changes (function input were changed, remember to update all!).
- [x] Document the test function(s).
- [x] Check the that the code passes the tests.
- [x] Write the test in the pytest module.

Ideas for tests:

- Make sure the end_season is at least equal to or grater than the start_season.
- Ensure the start_season and end_season are of the appropriate type.
- Ensure the `regular` and `playoffs` are boolean values
- Make sure the start_season and end_season are valid dates to query.
  - Update the documentation describing what the valid dates are.
- Make sure the default values for the current season are appropriate (i.e. if the arguments are left blank).
- Check that the function returns plot based on the correct subset of original data frame.
- Check that the API request returns a valid response. 
  - This could either be an assert, and/or a try/catch statement. 
- Implement a system to handle when bad responses are returned (either start_season or end_season is 2004)
- Identify why a bad response was made.
