### ISSUE TITLE
Milestone 3 Deliverables

### ISSUE THREAD

**Issue by jnederlo** [UBC-MDS/pypuck#42]
**Continuous Integration (CI)**
 - [x] Set up GitHub Actions for Continuous Integration (CI) and Continuous Deployment (CD).

**Integration tests**
- [x] Add adequate integration tests.
- [x] Ensure the build status and GitHub Action logs show passing.

**Additional tests**
- [x] Add additional test cases.
- [x] Ensure minimum 90% branch coverage.
- [x] The codecov.io button on the repo must communicate the coverage.

**Documentation**
- [x] Ensure documentation is valid and up-to-date on "Read the Docs".
- [x] Include usage (runnable example) and installation instructions in README.
- [x] Add in any missing docstrings and/or script headers.
- [x] Review the PyOpenSci package reviewer guides and checklists to make sure the package 

**Final Check**
- [x] Before submission, all GitHub Actions workflows should run without error and be advertised as such using badges in the README.
